"""Warm automatic replies to incoming WhatsApp messages (owner's decision P6, 2026-10-08).

Fixed, reviewed texts, never generated by a model: a model could slip clinical advice into
a chat no professional has seen. The reply depends only on the message's intent
(`crisis.classify`); the text of the message is never stored or used otherwise.

- **crisis**: always, at once. Containment, the news that a professional was alerted
  (the on-call escalation runs in parallel, ADR 0017), and the emergency lines. Repeated at
  most every 10 minutes, so a person writing many messages is not flooded.
- **human**: a person of the team was told and will write back soon.
- **other**: a welcome with a short menu, at most once every 12 hours per number.
- **stop**: a kind confirmation of the opt-out.

Emergency lines verified on 2026-10-08 at the Ministry of Public Health's own page
(https://www.salud.gob.ec/a-traves-de-la-linea-171-msp-ofrece-atencion-en-salud-mental/,
dated 2023-01-16): line 171 option 6, psychological first aid, every day incl. holidays
07:00-20:00; ECU 911 for emergencies. Configurable (`CRISIS_HELP_TEXT`): review them with
the practice and the lawyer (L3) and update them if the Ministry changes them.
"""

from __future__ import annotations

from datetime import timedelta

from orchestrator.crisis import Intent

# The least time between two automatic replies of the same kind to the same number.
REPLY_EVERY: dict[Intent, timedelta] = {
    "crisis": timedelta(minutes=10),
    "human": timedelta(minutes=30),
    "other": timedelta(hours=12),
    "stop": timedelta(0),
}

DEFAULT_CRISIS_HELP = (
    "Si estás en peligro ahora o piensas hacerte daño, por favor llama ya al ECU 911. "
    "También puedes llamar gratis a la Línea 171, opción 6, del Ministerio de Salud Pública "
    "(primeros auxilios psicológicos, todos los días de 7:00 a 20:00)."
)


def reply_text(intent: Intent, practice: str, crisis_help: str) -> str:
    if intent == "crisis":
        return (
            "Gracias por escribirnos y por contarnos cómo te sientes. No estás sola ni solo 💙\n"
            f"Ya avisamos a una profesional de {practice} para que se comunique contigo "
            "lo antes posible.\n"
            f"{crisis_help}"
        )
    if intent == "human":
        return (
            "¡Claro que sí! 😊 Ya le avisamos a una persona del equipo de "
            f"{practice}; te escribirá lo antes posible dentro de nuestro horario de atención.\n"
            "Si se trata de una emergencia, llama al ECU 911."
        )
    if intent == "stop":
        return (
            "Listo, ya no te enviaremos mensajes informativos ni promocionales. "
            "Si algún día necesitas algo, aquí estaremos 💙"
        )
    return (
        f"¡Hola! 👋 Gracias por escribir a {practice}. Nos alegra saber de ti.\n"
        "• Para agendar o cambiar una cita, usa nuestra app o escríbenos el día y la hora "
        "que prefieres y te ayudamos.\n"
        "• Si quieres hablar con una persona del equipo, escribe «persona».\n"
        "Te respondemos en horario de atención. Este chat no atiende emergencias: si estás "
        "en peligro, llama al ECU 911."
    )
