"""Marketing creatives generated by code (ADR 0015, M2): infographics as JPEG and short
slideshow videos as MP4 with H.264, the formats Instagram and TikTok accept.

Rules that do not depend on who asks:

* **The copy is checked before anything is drawn.** Every line goes through the pack's
  copy rules (`risk.check_copy`: banned claims, clinical details); if it fails, no file is
  written, so an image with forbidden content never exists.
* **No personal data has a place to go.** A `Brief` holds a title, a few points, a call to
  action and the practice's name; there is no field for a patient.
* **Health packs carry a fixed footer** saying the content is informative and does not
  replace a consultation. This is a product choice, not a cited legal requirement (the
  advertising rules for clinics are the lawyer's question H1).
* **Videos have no audio track**: music needs its own licence.
* **ffmpeg runs as a separate program** with an argument list (never a shell), a timeout,
  and inputs written to a private temporary directory."""

from __future__ import annotations

import hashlib
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from PIL import Image, ImageDraw, ImageFont
from pydantic import BaseModel, Field, field_validator

from orchestrator.config import Settings
from orchestrator.packs import Pack
from orchestrator.risk import check_copy
from orchestrator.social import Network, PublishCheck, check_publish

Format = Literal["feed", "story", "square"]
# Instagram feed portrait (4:5), stories / TikTok (9:16) and square.
SIZES: dict[Format, tuple[int, int]] = {
    "feed": (1080, 1350),
    "story": (1080, 1920),
    "square": (1080, 1080),
}
HEALTH_FOOTER = "Contenido informativo. No reemplaza una consulta profesional."
HEX = r"^#[0-9a-fA-F]{6}$"
MARGIN = 90


class Brief(BaseModel):
    title: str = Field(min_length=1, max_length=80)
    points: list[str] = Field(min_length=1, max_length=5)
    cta: str = Field(default="", max_length=80)
    practice_name: str = Field(min_length=1, max_length=80)
    background: str = Field(default="#F7F3EE", pattern=HEX)
    accent: str = Field(default="#2F6F73", pattern=HEX)
    text: str = Field(default="#1F2933", pattern=HEX)

    @field_validator("title", "practice_name")
    @classmethod
    def _not_blank(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("must not be blank")
        return value.strip()

    @field_validator("points")
    @classmethod
    def _short_points(cls, value: list[str]) -> list[str]:
        points = [p.strip() for p in value]
        if any(not p or len(p) > 120 for p in points):
            raise ValueError("each point needs 1 to 120 characters")
        return points

    def all_text(self) -> str:
        return "\n".join([self.title, *self.points, self.cta, self.practice_name])


class CreativeRejected(ValueError):
    """The copy breaks the pack's rules; nothing was rendered."""

    def __init__(self, violations: list[str]) -> None:
        super().__init__(f"copy rejected: {violations}")
        self.violations = violations


class CreativeUnavailable(RuntimeError):
    """The tool needed for this creative (ffmpeg) is not installed."""


class CreativeError(RuntimeError):
    """Rendering failed."""


@dataclass(frozen=True)
class Creative:
    path: Path
    media_type: Literal["image", "video"]
    media_format: Literal["jpeg", "mp4"]
    width: int
    height: int
    sha256: str
    needs_owner_approval: bool

    def preflight(
        self, network: Network, *, public_url: bool = False, audited: bool = False
    ) -> PublishCheck:
        """What the platform would say about this file (social.check_publish)."""
        return check_publish(
            network,
            media_type=self.media_type,
            media_format=self.media_format,
            public_url=public_url,
            audited=audited,
        )


def vet(brief: Brief, pack: Pack) -> bool:
    """Apply the pack's copy rules; return whether the owner must also approve."""
    check = check_copy(brief.all_text(), pack)
    if not check.ok:
        raise CreativeRejected(check.violations)
    return check.needs_owner_approval


def footer_lines(brief: Brief, pack: Pack) -> list[str]:
    lines = [brief.practice_name]
    if pack.review.clinical:
        lines.append(HEALTH_FOOTER)
    return lines


# --- drawing ----------------------------------------------------------------------------


# Atkinson Hyperlegible (SIL OFL 1.1, licence next to the files): Pillow's built-in font
# has no Spanish accented letters, which rendered "también" as "tambi□n".
FONTS_DIR = Path(__file__).parent / "assets" / "fonts"


def _font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    name = "AtkinsonHyperlegible-Bold.ttf" if bold else "AtkinsonHyperlegible-Regular.ttf"
    return ImageFont.truetype(FONTS_DIR / name, size)


def _wrap(draw: ImageDraw.ImageDraw, text: str, font: object, width: int) -> list[str]:
    lines: list[str] = []
    current = ""
    for word in text.split():
        candidate = f"{current} {word}".strip()
        if draw.textlength(candidate, font=font) <= width or not current:  # type: ignore[arg-type]
            current = candidate
        else:
            lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def _block(
    draw: ImageDraw.ImageDraw,
    text: str,
    *,
    top: int,
    size: int,
    fill: str,
    width: int,
    left: int = MARGIN,
    bold: bool = False,
) -> int:
    """Draw wrapped text and return the y below it."""
    font = _font(size, bold)
    for line in _wrap(draw, text, font, width):
        draw.text((left, top), line, font=font, fill=fill)
        top += int(size * 1.25)
    return top


def _canvas(brief: Brief, fmt: Format) -> tuple[Image.Image, ImageDraw.ImageDraw]:
    image = Image.new("RGB", SIZES[fmt], brief.background)
    draw = ImageDraw.Draw(image)
    draw.rectangle((0, 0, SIZES[fmt][0], 24), fill=brief.accent)
    return image, draw


def _footer(draw: ImageDraw.ImageDraw, brief: Brief, pack: Pack, fmt: Format) -> None:
    width, height = SIZES[fmt]
    lines = footer_lines(brief, pack)
    top = height - MARGIN - 44 * len(lines)
    draw.line((MARGIN, top - 30, width - MARGIN, top - 30), fill=brief.accent, width=3)
    for i, line in enumerate(lines):
        size = 34 if i == 0 else 26
        _block(draw, line, top=top, size=size, fill=brief.text, width=width - 2 * MARGIN)
        top += 44


def draw_infographic(brief: Brief, pack: Pack, fmt: Format = "feed") -> Image.Image:
    image, draw = _canvas(brief, fmt)
    width = SIZES[fmt][0] - 2 * MARGIN
    top = _block(
        draw, brief.title, top=MARGIN + 40, size=72, fill=brief.accent, width=width, bold=True
    )
    top += 40
    for point in brief.points:
        draw.ellipse((MARGIN, top + 14, MARGIN + 26, top + 40), fill=brief.accent)
        top = _block(
            draw, point, top=top, size=42, fill=brief.text, width=width - 60, left=MARGIN + 50
        )
        top += 28
    if brief.cta:
        top += 20
        box = (MARGIN, top, SIZES[fmt][0] - MARGIN, top + 110)
        draw.rounded_rectangle(box, radius=24, fill=brief.accent)
        _block(
            draw,
            brief.cta,
            top=top + 30,
            size=44,
            fill=brief.background,
            width=width - 60,
            left=MARGIN + 30,
            bold=True,
        )
    _footer(draw, brief, pack, fmt)
    return image


def draw_slides(brief: Brief, pack: Pack, fmt: Format = "story") -> list[Image.Image]:
    """One slide for the title, one per point, and one for the call to action."""
    width = SIZES[fmt][0] - 2 * MARGIN
    texts = [
        (brief.title, 84, brief.accent, True),
        *((p, 60, brief.text, False) for p in brief.points),
    ]
    if brief.cta:
        texts.append((brief.cta, 72, brief.accent, True))
    slides = []
    for text, size, fill, bold in texts:
        image, draw = _canvas(brief, fmt)
        _block(draw, text, top=SIZES[fmt][1] // 3, size=size, fill=fill, width=width, bold=bold)
        _footer(draw, brief, pack, fmt)
        slides.append(image)
    return slides


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


# --- rendering to files -----------------------------------------------------------------


def render_infographic(brief: Brief, pack: Pack, out: Path, fmt: Format = "feed") -> Creative:
    owner = vet(brief, pack)
    image = draw_infographic(brief, pack, fmt)
    out.parent.mkdir(parents=True, exist_ok=True)
    image.save(out, format="JPEG", quality=90, optimize=True)
    width, height = image.size
    return Creative(out, "image", "jpeg", width, height, _sha256(out), owner)


def ffmpeg_path(settings: Settings) -> str | None:
    return shutil.which(settings.ffmpeg_binary)


def render_video(
    brief: Brief,
    pack: Pack,
    out: Path,
    settings: Settings,
    fmt: Format = "story",
    seconds_per_slide: int = 3,
) -> Creative:
    owner = vet(brief, pack)
    binary = ffmpeg_path(settings)
    if binary is None:
        raise CreativeUnavailable(f"ffmpeg not found ({settings.ffmpeg_binary!r})")
    out.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="creative-") as tmp:
        for i, slide in enumerate(draw_slides(brief, pack, fmt)):
            slide.save(Path(tmp) / f"slide_{i:02d}.png", format="PNG")
        command = [
            binary,
            "-y",
            "-hide_banner",
            "-loglevel",
            "error",
            "-framerate",
            f"1/{seconds_per_slide}",
            "-i",
            str(Path(tmp) / "slide_%02d.png"),
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",  # what phones and TikTok play
            "-r",
            "30",
            "-movflags",
            "+faststart",
            "-an",  # no audio: music needs its own licence
            str(out),
        ]
        try:
            subprocess.run(  # noqa: S603 - fixed argument list, no shell, binary from settings
                command, check=True, capture_output=True, timeout=settings.ffmpeg_timeout_seconds
            )
        except subprocess.CalledProcessError as exc:
            tail = exc.stderr.decode("utf-8", "replace")[-300:] if exc.stderr else ""
            raise CreativeError(f"ffmpeg failed: {tail.strip()}") from exc
        except subprocess.TimeoutExpired as exc:
            raise CreativeError("ffmpeg timed out") from exc
    width, height = SIZES[fmt]
    return Creative(out, "video", "mp4", width, height, _sha256(out), owner)
