"""baseline: schema of cfd0c85

Revision ID: 0001
Revises:
Create Date: 2026-10-01 09:54:52.539607

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource", sa.String(length=256), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant", "seq", name="uq_audit_tenant_seq"),
    )
    op.create_index(
        op.f("ix_audit_events_subject_id"), "audit_events", ["subject_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_tenant"), "audit_events", ["tenant"], unique=False)
    op.create_index(op.f("ix_audit_events_ts"), "audit_events", ["ts"], unique=False)
    op.create_table(
        "audit_heads",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("tenant"),
    )
    op.create_table(
        "campaign_recipients",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("campaign_id", sa.String(length=64), nullable=False),
        sa.Column("patient_id", sa.String(length=64), nullable=False),
        sa.Column("arm", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fallback_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("tenant", "campaign_id", "patient_id"),
    )
    op.create_table(
        "campaigns",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("segment", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("holdout_pct", sa.Integer(), nullable=False),
        sa.Column("compliance", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("approved_by", sa.String(length=128), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_version", sa.Integer(), nullable=True),
        sa.Column("approved_hash", sa.String(length=64), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("tenant", "id"),
    )
    op.create_table(
        "consents",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("tenant", "subject_id", "purpose"),
    )
    op.create_table(
        "contact_budget",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("patient_id", sa.String(length=64), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("used", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("tenant", "patient_id", "period"),
    )
    op.create_table(
        "crm_appointments",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("patient_id", sa.String(length=64), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_min", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant", "id"),
    )
    op.create_index(
        op.f("ix_crm_appointments_patient_id"), "crm_appointments", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_crm_appointments_starts_at"), "crm_appointments", ["starts_at"], unique=False
    )
    op.create_table(
        "crm_clinical_notes",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("patient_id", sa.String(length=64), nullable=False),
        sa.Column("messages", sa.JSON(), nullable=False),
        sa.Column("review", sa.JSON(), nullable=True),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant", "thread_id"),
    )
    op.create_index(
        op.f("ix_crm_clinical_notes_patient_id"), "crm_clinical_notes", ["patient_id"], unique=False
    )
    op.create_table(
        "crm_patients",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("telegram_chat_id", sa.String(length=64), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("preferred_channel", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("restricted", sa.Boolean(), nullable=False),
        sa.Column("erased_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("tenant", "id"),
    )
    op.create_table(
        "crm_treatments",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("patient_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("presented_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant", "id"),
    )
    op.create_index(
        op.f("ix_crm_treatments_patient_id"), "crm_treatments", ["patient_id"], unique=False
    )
    op.create_table(
        "principals",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("roles", sa.JSON(), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=True),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("tenant", "id"),
    )
    op.create_index(op.f("ix_principals_key_hash"), "principals", ["key_hash"], unique=True)
    op.create_table(
        "reviews",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subject_id", sa.String(length=64), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("decision", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("tenant", "thread_id"),
    )
    op.create_index(op.f("ix_reviews_status"), "reviews", ["status"], unique=False)
    op.create_table(
        "subject_threads",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("subject_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant", "thread_id"),
    )
    op.create_index(
        op.f("ix_subject_threads_subject_id"), "subject_threads", ["subject_id"], unique=False
    )
    op.create_table(
        "thread_leases",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("holder", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant", "thread_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thread_leases")
    op.drop_index(op.f("ix_subject_threads_subject_id"), table_name="subject_threads")
    op.drop_table("subject_threads")
    op.drop_index(op.f("ix_reviews_status"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_principals_key_hash"), table_name="principals")
    op.drop_table("principals")
    op.drop_index(op.f("ix_crm_treatments_patient_id"), table_name="crm_treatments")
    op.drop_table("crm_treatments")
    op.drop_table("crm_patients")
    op.drop_index(op.f("ix_crm_clinical_notes_patient_id"), table_name="crm_clinical_notes")
    op.drop_table("crm_clinical_notes")
    op.drop_index(op.f("ix_crm_appointments_starts_at"), table_name="crm_appointments")
    op.drop_index(op.f("ix_crm_appointments_patient_id"), table_name="crm_appointments")
    op.drop_table("crm_appointments")
    op.drop_table("contact_budget")
    op.drop_table("consents")
    op.drop_table("campaigns")
    op.drop_table("campaign_recipients")
    op.drop_table("audit_heads")
    op.drop_index(op.f("ix_audit_events_ts"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_tenant"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_subject_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
