"""campaign mode and population, versioned knowledge documents

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 09:55:02.412822

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_documents",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("doc_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("chunks", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant", "doc_id"),
    )
    op.create_table(
        "knowledge_versions",
        sa.Column("tenant", sa.String(length=64), nullable=False),
        sa.Column("doc_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant", "doc_id", "version"),
    )
    # Campaigns sent before this revision were live sends. Without a server default the
    # NOT NULL column cannot be added to a table that already has rows.
    op.add_column(
        "campaigns",
        sa.Column("mode", sa.String(length=16), nullable=False, server_default="live"),
    )
    op.add_column("campaigns", sa.Column("population", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("campaigns", "population")
    op.drop_column("campaigns", "mode")
    op.drop_table("knowledge_versions")
    op.drop_table("knowledge_documents")
    # ### end Alembic commands ###
