#!/usr/bin/env bash
# One-time setup of the single-node production stack (ADR 0021) on a fresh Ubuntu
# 22.04/24.04 server, amd64 or arm64 (an Oracle Cloud "Always Free" Ampere VM works):
#
#   git clone https://github.com/tatymarisol44-cmyk/Tatos.git && cd Tatos
#   sudo bash deploy/single-node/install.sh [--tenant clinica] [--pack ec-psychologist]
#
# Options: --dir DIR (default /opt/agency), --image REPO@sha256:... (default: the image
# CI built and signed from main), --no-tunnel (no public entrance), --no-timer (no
# nightly backup), --skip-docker (Docker is already there and you are not root).
# Re-running it is safe: secrets are generated only once, and it deploys again.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
dir=/opt/agency
image=""
tenant=clinica
pack=ec-psychologist
tunnel=1
timer=1
docker_install=1
REPO_IMAGE="ghcr.io/tatymarisol44-cmyk/agency-orchestrator"

while [ $# -gt 0 ]; do
  case "$1" in
    --dir) dir="$2"; shift 2 ;;
    --image) image="$2"; shift 2 ;;
    --tenant) tenant="$2"; shift 2 ;;
    --pack) pack="$2"; shift 2 ;;
    --no-tunnel) tunnel=0; shift ;;
    --no-timer) timer=0; shift ;;
    --skip-docker) docker_install=0; shift ;;
    *) echo "unknown option $1" >&2; exit 2 ;;
  esac
done
[[ "$tenant" =~ ^[A-Za-z0-9_.-]{1,64}$ ]] || { echo "invalid --tenant" >&2; exit 2; }
[[ "$pack" =~ ^[a-z0-9-]{1,64}$ ]] || { echo "invalid --pack" >&2; exit 2; }

say() { printf '\n== %s\n' "$*"; }

if ! command -v docker > /dev/null && [ "$docker_install" = 1 ]; then
  say "installing Docker Engine from Docker's signed apt repository"
  [ "$(id -u)" = 0 ] || { echo "run as root (sudo) to install Docker" >&2; exit 1; }
  . /etc/os-release
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL "https://download.docker.com/linux/$ID/gpg" -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/$ID $VERSION_CODENAME stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
fi
docker compose version > /dev/null

say "files in $dir"
mkdir -p "$dir"
install -m 0644 "$here/compose.yaml" "$dir/compose.yaml"
install -m 0755 "$here/deploy.sh" "$here/backup.sh" "$dir/"

if [ ! -f "$dir/.env" ]; then
  say "generating secrets (once; kept in $dir/.env, mode 600)"
  rand() { openssl rand -hex "$1"; }
  service_key="svc_$(rand 24)"
  umask 077
  cat > "$dir/.env" <<EOF
# Generated by install.sh on $(date -u +%FT%TZ). Private: never commit or share it.
# The API reads it; Compose reads it for \${...} in compose.yaml.
COMPOSE_PROFILES=$([ "$tunnel" = 1 ] && echo quick-tunnel)
API_IMAGE=
POSTGRES_PASSWORD=$(rand 24)
# The practice's service key (admin of tenant $tenant). Give people their own keys:
#   POST /v1/admin/staff with this key.
API_KEYS=$service_key:$tenant
TENANT_PACKS={"$tenant":"$pack"}
PSEUDONYM_KEY=$(rand 32)
META_APP_SECRET=$(rand 32)
WHATSAPP_VERIFY_TOKEN=$(rand 16)
# Language model. Without a provider key the offline model answers with fixed texts:
# set ANTHROPIC_API_KEY=... and LLM_BACKEND=litellm (after signing its DPA, docs/legal).
LLM_BACKEND=fake
LLM_FALLBACK_MODELS=[]
# Hashing embeddings: no message text leaves the server for routing (no extra sub-processor).
EMBEDDING_BACKEND=hashing
PRACTICE_DISPLAY_NAME=Consultorio
# Off-server backups (Cloudflare R2 or any S3), see backup.sh:
BACKUP_REMOTE=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
BACKUP_KEEP_DAYS=14
# For your own domain: create a named tunnel in Cloudflare Zero Trust, then
# COMPOSE_PROFILES=tunnel and TUNNEL_TOKEN=... (and PUBLIC_BASE_URL=https://your.domain)
TUNNEL_TOKEN=
EOF
  chmod 600 "$dir/.env"
fi

if [ -z "$image" ]; then
  say "resolving the image CI built from main"
  image="$REPO_IMAGE@$(docker buildx imagetools inspect "$REPO_IMAGE:main" --format '{{json .Manifest}}' \
    | python3 -c 'import json, sys; print(json.load(sys.stdin)["digest"])')"
fi

if [ "$timer" = 1 ] && command -v systemctl > /dev/null && [ "$(id -u)" = 0 ]; then
  say "nightly backup (systemd timer agency-backup, 03:15 UTC)"
  cat > /etc/systemd/system/agency-backup.service <<EOF
[Unit]
Description=Back up the agency single-node stack
After=docker.service
[Service]
Type=oneshot
ExecStart=$dir/backup.sh
EOF
  cat > /etc/systemd/system/agency-backup.timer <<EOF
[Unit]
Description=Nightly backup of the agency single-node stack
[Timer]
OnCalendar=*-*-* 03:15:00 UTC
Persistent=true
[Install]
WantedBy=timers.target
EOF
  systemctl daemon-reload
  systemctl enable --now agency-backup.timer
fi

say "deploying $image"
"$dir/deploy.sh" "$image"

if [ "$tunnel" = 1 ]; then
  say "public address (Cloudflare quick tunnel)"
  for _ in $(seq 1 30); do
    url="$(cd "$dir" && docker compose logs tunnel-quick 2>/dev/null | grep -o 'https://[a-z0-9-]*\.trycloudflare\.com' | tail -1)"
    [ -n "$url" ] && break
    sleep 2
  done
  echo "${url:-not ready yet: cd $dir && docker compose logs tunnel-quick}"
  echo "(a quick-tunnel address changes when the tunnel restarts; use a named tunnel on a domain for a fixed one)"
fi
say "done"
echo "service key: sed -n 's/^API_KEYS=//p' $dir/.env   (keep it secret)"
echo "redeploy:    $dir/deploy.sh <image@sha256:...>     backup now: $dir/backup.sh"
